version: "2" # required to adjust maintainability checks
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  method-lines:
    config:
      threshold: 300
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    config:
      threshold: 30
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false
exclude_patterns:
  ############################################
  ## Code Climate's default exclude patterns
  ############################################
  - config/
  - db/
  - dist/
  - features/
  - "**/node_modules/"
  - script/
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - Tests/
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  ############################################

  ############################################
  ## Additional exclude patterns
  - src/assets
  - examples/*
  ############################################
